profile-name: local

spring:
  application:
    name: module-common
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3308/common?serverTimezone=Asia/Seoul
    username: common_user
    password: commonpw123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
