version: "3.8"
services:
  mysql:
    container_name: mysql_common
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=common
      - MYSQL_USER=common_user
      - MYSQL_PASSWORD=commonpw123
      - MYSQL_ROOT_PASSWORD=commonpw123
      - TZ=Asia/Seoul